### PR TITLE
Code to check a csv file for certain columns

### PR DESCRIPTION
**Pull request by msecret**

### CODE REVIEW

**Comment by bsweger** [comment]
Hi Marco,

This looks great. The updated .csv files with new column names are over in this branch:  https://github.com/18F/data-act-pilot/tree/110-update-csv-columns

What's the easier way to handle this from your perspective? Should I create a separate PR for them, or do you want them in this PR?

**Comment by msecret** [comment]
@bsweger I think creating a PR for them. This branch needs heavy work because of the work I just did with Andrew, so I might move it to a new PR anyway.

**Comment by bsweger** [comment]
@msecret will do--thanks!

**Comment by bsweger** [comment]
@msecret saw this was still sitting out here? is this still a PR you want to merge, or did it get supplanted by something else?

**Comment by msecret** [comment]
This change isn't needed anymore as it was overwritten by another one

**Pull request closed without merging**
