### PR TITLE
Row identifier

### PR DESCRIPTION
**Pull request by msecret**
We're attempting to provide an identifier so the user can fix the
data back in their system at the source. Becky suggested these
combination of fields to get the TAS.

Currently, the logic is if the field doesn't exist in the data, just
not include it. This might not be the best logic because it
make make the number more confusing. Another option is to include
the number 0 where the data doesn't exist. This depends on what
the user would expect.

screen shot 2015-08-21 at 3 31 23 pm

### CODE REVIEW

**Comment by bsweger** [comment]
Thanks @msecret! I think your approach of excluding missing data is fine to show--we can solicit additional feedback. One tweak I'd make is to separate the individual keys with spaces instead of hyphens. The exception is the individual fields that make up the component TAS...those are arguably a single entity, and I think the hyphens are useful to indicate that.

So the example above would read:

```Row: 14, 73-400 20256 4110```

Because 73-400 make up the TAS, and object class/program activity are separate fields (sorry I wasn't more clear in #102 about that distinction).

Lastly, what do you think about prefixing the values with the actual name of the field? This is more tricky because we'd probably want to lump that TAS component fields into a single TAS label. I don't have strong feelings here...might be a question for the review:

```Row: 14, TAS = 73-400 ProgramActivity = 20256 ObjectClass = 4110```

**Comment by msecret** [comment]
@bsweger, I do think prefixing the fields would be better. This is what I'll work on.

Also: what are the exact fields that make up the TAS? IS that different for each type of the 4 templates?

**Comment by bsweger** [comment]
@msecret In spreadsheets where the TAS appears (which is all of them except for award.csv), the fields that compose it are:

* AllocationTransferAgencyIdentifier
* AgencyIdentifier
* BeginningPeriodOfAvailability
* EndingPeriodOfAvailability
* AvailabilityTypeCode
* MainAccountCode

Should be the same list of fields in all three cases (appropriations, award_financial, and object_class_program_activity). Thanks!

**Comment by msecret** [comment]
Updated design:

screen shot 2015-08-24 at 5 03 29 pm

**Pull request merged**
