### PR TITLE
added web app copy

### LINKED ISSUE #174: Content Feedback
Feedback on content: 

* Do you have to validate all four files? Needs some instruction on all or some of the files?  Something like, "You can validate all four files but if you want to check one you can”
* Capitalize Me in “Validate Me”
* Do the users using the broker know what each of the files mean?

### PR DESCRIPTION
**Pull request by elainekamlley**
@msecret -- this is ready for review. They are minor changes but maybe adds a little more clarity to the user. This will close #174 

Also, this copy will likely change once the conversion feature is in place.

### CODE REVIEW

**Comment by bsweger** [comment]
Thanks @elainekamlley. Now that we have @emileighoutlaw's blessing on the documentation re-org, can we link to the how-to somewhere on the website (and maybe have it open in another tab?). Once merged, HOWTO.md will live in docs/HOWTO.md.

Also, what do you think about adding some text to the gray box on the left-hand side of the site to emphasize that this isn't fully featured, etc. Can probably crib some text from HOWTO, something like:
> This prototype is a sandbox where you can test your agency's DATA Act files against the data standard as it evolves.
>
>Find out more, including how to use the site and prepare your data in our [how-to guide](#)

**Comment by elainekamlley** [comment]
@bsweger I love it. I'll add it now.

**Comment by elainekamlley** [comment]
edited a little: 

>This prototype is a sandbox where you can test your agency's federal spending data against the 
<a href="http://fedspendingtransparency.github.io/data-exchange-standard/"> DATA Act standard</a> as it evolves.
>Find out more, including how to use the site and prepare your agency data in our <a href="">how-to guide</a>

**Comment by emileighoutlaw** [comment]
I like it!

**Comment by bsweger** [comment]
Yes, thanks @elainekamlley. Does the second sentence need a comma after _agency data_?

**Comment by emileighoutlaw** [comment]
Ah yes. I think it should probably be:

Find out more — including how to use the site and prepare your agency data
— in our how to guide.


Also, strictly speaking, the hyphen is optional in this type of compound
adjective. We try to avoid it, unless we think readers will be confused. In
this case, I think everyone will understand what a "how to guide" is.

**Comment by elainekamlley** [comment]
Made that edit @emileighoutlaw and @bsweger

**Comment by bsweger** [comment]
It would also be great if we could somehow incorporate artisanal mixologists into the website copy.

**Comment by bsweger** [comment]
Thanks, @elainekamlley! If @msecret is cool with this, then let us merge!

**Comment by elainekamlley** [comment]
@bsweger haha. I mean what are we doing if not artisanally mixing data?

**Pull request merged**
