### PR TITLE
Add flask web app

### PR DESCRIPTION
**Pull request by msecret**
This adds a basic flask web app to the project.

I was having trouble installing certain dependencies, like pandas,
this will have to be resolved.

### CODE REVIEW

**Comment by bsweger** [comment]
Thanks, @msecret. Let me know if I can help with pandas. Also, should we be committing the SAM API here?

**Comment by msecret** [comment]
@bsweger I'm a little confused with how we're using the SAM API. Or what it is. Could you explain what you were expecting, or maybe we could organize a meeting if that would be easier?

**Comment by bsweger** [comment]
My question mostly was...should we be putting a real SAM api key in the repo? But you're right on to ask what SAM is and why we need it. Quick overview below for transparency....happy to fill in more details synchronously.

There's no definitive answer yet on how the SAM API integrates with the DATA Act process. Essentially, as part of the DATA Act, Treasury will publish information about who receives money (vendor names, addresses, etc.) These vendors are uniquely identified by a DUNS number. 

SAM is a central repository of recipient info maintained by GSA. It has a public API (which we use in this pilot) and a WSDL thing that is used by internal apps (I think...I'm not a SAM expert). So the question is...should agencies:

* submit a DUNS to Treasury and let Treasury fill in the rest of the recipient info (from SAM)?
* use the DUNS to grab recipient info from SAM in real time as they submit DATA Act data?
* submit the recipient info that's stored in their awards system (which likely originally came from SAM).

related: https://github.com/18F/data-act-pilot/issues/47

**Comment by msecret** [comment]
I understand now. I changed the code to not include it anymore

**Pull request merged**
